# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rebels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=256, unique=True)),
                ('article_url', models.URLField()),
                ('body', models.TextField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('is_deleted', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('is_deleted', models.IntegerField(default=1)),
                ('articleId', models.ManyToManyField(to='rebels.Article')),
                ('userId', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('rss_url', models.URLField()),
                ('rssId', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('is_deleted', models.IntegerField(default=1)),
                ('hasRSS', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='article',
            name='provider',
            field=models.ManyToManyField(to='rebels.RSS'),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
