# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebels', '0002_auto_20180326_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasread',
            name='has_read_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
