# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rebels', '0002_auto_20180319_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasRSS', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='rss',
            old_name='rss_url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='rss',
            old_name='category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='suggested',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rss',
            name='hasRSS',
        ),
        migrations.RemoveField(
            model_name='rss',
            name='provider',
        ),
        migrations.AddField(
            model_name='rss',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userrss',
            name='suggested',
            field=models.ManyToManyField(to='rebels.RSS'),
        ),
    ]
