# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebels', '0003_auto_20180320_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='date_rss',
            field=models.DateField(auto_now=True),
        ),
    ]
