# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('is_deleted', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleRss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rebels.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('articleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rebels.Article')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('rssId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=256, null=True)),
                ('date_rss', models.DateField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=128, null=True)),
                ('last', models.CharField(max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rebels.RSS')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articlerss',
            name='rssId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rebels.RSS'),
        ),
    ]
