# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebels', '0002_auto_20180324_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
