# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rebels', '0004_auto_20180325_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hasread',
            name='articleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rebels.Article'),
        ),
        migrations.AddField(
            model_name='hasread',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
